import { Rewrite } from 'next/dist/lib/load-custom-routes'
import React from 'react'
import Layout from '../components/Layout'

type TRewrites = Record<'beforeFiles' | 'afterFiles', Rewrite[]>

const RewritesPage = () => (
  <Layout title="Rewrites | next-translate-routes Example">
    <h1>Rewrites</h1>
    <p>Here are the rewrites automatically generated by next-translate-routes:</p>
    <ul style={{ background: '#222', color: '#ddd', fontFamily: 'monospace', padding: '20px', listStyle: 'none' }}>
      {'['}
      {typeof window !== 'undefined'
        ? (window.__BUILD_MANIFEST.__rewrites as unknown as TRewrites).afterFiles.map((rewrite, i) => (
            <li key={i} style={{ marginLeft: '20px' }}>
              {'{'}
              {Object.entries(rewrite).map(([key, value]) => (
                <p style={{ margin: '5px 20px' }} key={key}>{`${key}: '${value}',`}</p>
              ))}
              {'},'}
            </li>
          ))
        : null}
      {']'}
    </ul>
  </Layout>
)

export default RewritesPage
